export default {
  invalidPassphrase: 'invalidPassphrase',
  QRCodeScanningError: 'QRCodeScanningError',
  accountDataError: 'accountDataError',
  failedDisplayingAccountData: 'failedDisplayingAccountData',
  QRCodeGenrationFailed: 'QRCodeGenrationFailed',
  QRCodeSetupFailed: 'QRCodeSetupFailed',
  failedPaymentsDataDisplay: 'failedPaymentsDataDisplay',
  failedToAssignHandlersToPayments: 'failedToAssignHandlersToPayments',
  promptError: 'promptError',
  failedToAssignHandlers: 'failedToAssignHandlers',
  cannotConnectToChat: 'cannotConnectToChat',
  failedToAssignonMessageHandlers: 'failedToAssignonMessageHandlers',
  messageIsTooLong: 'messageIsTooLong',
  failedToAssignEventListeners: 'failedToAssignEventListeners',
  failedToConnectToTheAccount: 'failedToConnectToTheAccount',
  failedToAssignGenericErrorsHandler: 'failedToAssignGenericErrorsHandler',
  failedRetrivingPayments: 'failedRetrivingPayments',
  failedLodingConversationTitle: 'failedLodingConversationTitle',
  invalidRecipientAddress: 'invalidRecipientAddress',
  FAILURE_INSUFFICIENT_BALANCE: 'FAILURE_INSUFFICIENT_BALANCE'
}
